# fly.toml app configuration file generated for cookbot on 2023-07-13T13:21:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cookbot"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  YTDL_NO_UPDATE = "1"

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 0
  processes = ["app"]
