# fly.toml app configuration file generated for cookbot on 2023-07-13T09:29:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cookbot"
primary_region = "sin"

[env]
  YTDL_NO_UPDATE = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
