export const PLAY_MUSIC = 'Music playing now: '
export const PAUSE_MUSIC = 'Paused the song for you'
export const RESUME_MUSIC = 'Resumed the song for you :)'
export const REPEAT_QUEUE = 'Repeat list song'
export const REPEAT_SONG = 'Repeat song'
export const REPEAT_OFF = 'Repeat off'
export const LIST_MUSIC = 'List music in queue: '
export const SKIP_SONG = 'Skipped! Now playing: '